//
// Created by 小老虎 on 2020/2/28.
// changyanlong
//

#ifndef FFMPEG_N4_1_3_CYL2ANALYZER_H
#define FFMPEG_N4_1_3_CYL2ANALYZER_H

#define CYL_ANALYZE_MB_TYPE_IS_INTRA4x4     "IS_INTRA4x4";
#define CYL_ANALYZE_MB_TYPE_IS_INTRA16x16   "IS_INTRA16x16";
#define CYL_ANALYZE_MB_TYPE_IS_PCM          "IS_PCM";
#define CYL_ANALYZE_MB_TYPE_IS_INTRA        "IS_INTRA";
#define CYL_ANALYZE_MB_TYPE_IS_INTER        "IS_INTER";
#define CYL_ANALYZE_MB_TYPE_IS_SKIP         "IS_SKIP";
#define CYL_ANALYZE_MB_TYPE_IS_INTRA_PCM    "IS_INTRA_PCM";
#define CYL_ANALYZE_MB_TYPE_IS_INTERLACED   "IS_INTERLACED";
#define CYL_ANALYZE_MB_TYPE_IS_DIRECT       "IS_DIRECT";
#define CYL_ANALYZE_MB_TYPE_IS_GMC          "IS_GMC";
#define CYL_ANALYZE_MB_TYPE_IS_16X16        "IS_16X16";
#define CYL_ANALYZE_MB_TYPE_IS_16X8         "IS_16X8";
#define CYL_ANALYZE_MB_TYPE_IS_8X16         "IS_8X16";
#define CYL_ANALYZE_MB_TYPE_IS_8X8          "IS_8X8";
#define CYL_ANALYZE_MB_TYPE_IS_SUB_8X8      "IS_SUB_8X8";
#define CYL_ANALYZE_MB_TYPE_IS_SUB_8X4      "IS_SUB_8X4";
#define CYL_ANALYZE_MB_TYPE_IS_SUB_4X8      "IS_SUB_4X8";
#define CYL_ANALYZE_MB_TYPE_IS_SUB_4X4      "IS_SUB_4X4";
#define CYL_ANALYZE_MB_TYPE_IS_ACPRED       "IS_ACPRED";
#define CYL_ANALYZE_MB_TYPE_IS_QUANT        "IS_QUANT";
#define CYL_ANALYZE_MB_TYPE_UnKnow          "UnKnow";

#endif //FFMPEG_N4_1_3_CYL2ANALYZER_H
